Repository openshift/kueue-operator, pull requests merged in 2025-08, with the labels that each got.

#519 remove coverity check from main pipelines
  .tekton/kueue-bundle-main-pull-request.yaml
  .tekton/kueue-bundle-main-push.yaml
  .tekton/kueue-must-gather-main-pull-request.yaml
  .tekton/kueue-must-gather-main-push.yaml
  .tekton/kueue-operator-main-pull-request.yaml
  .tekton/kueue-operator-main-push.yaml
Labels: approved, lgtm

#522 Added support for s390x for kueue-Operator
  .tekton/kueue-must-gather-main-pull-request.yaml
  .tekton/kueue-must-gather-main-push.yaml
  .tekton/kueue-operator-main-pull-request.yaml
  .tekton/kueue-operator-main-push.yaml
Labels: approved, lgtm, ok-to-test

#515 OCPNODE-3537: use main kueue for operator e2e
  Makefile
  bundle.Dockerfile
  hack/preserve-bundle-labels.sh
Labels: approved, lgtm, jira/valid-reference

#555 konflux: add hermetic builds to operand main
  .tekton/kueue-operand-main-pull-request.yaml
  .tekton/kueue-operand-main-push.yaml
  .tekton/kueue-operator-main-pull-request.yaml
  .tekton/kueue-operator-main-push.yaml
Labels: approved, lgtm

#559 related_images: use the latest images and use the latest hashes
  related_images.developer.json
Labels: approved, lgtm

#560 add architectures to must-gather image and tweak cel expressions
  .tekton/kueue-bundle-main-pull-request.yaml
  .tekton/kueue-bundle-main-push.yaml
  .tekton/kueue-must-gather-main-pull-request.yaml
  .tekton/kueue-must-gather-main-push.yaml
  .tekton/kueue-operator-main-pull-request.yaml
  .tekton/kueue-operator-main-push.yaml
Labels: approved, lgtm

#567 add hermetic builds for kueue operator and set cel expressions
  .tekton/kueue-bundle-1-1-pull-request.yaml
  .tekton/kueue-bundle-1-1-push.yaml
  .tekton/kueue-must-gather-1-1-pull-request.yaml
  .tekton/kueue-must-gather-1-1-push.yaml
  .tekton/kueue-operator-1-1-pull-request.yaml
  .tekton/kueue-operator-1-1-push.yaml
Labels: approved, lgtm

#574 developer bundle: skip checks (speeds up build)
  .tekton/kueue-bundle-dev-main-pull-request.yaml
  .tekton/kueue-bundle-dev-main-push.yaml
Labels: approved, lgtm
