Repository openshift/kueue-operator, pull requests merged in 2025-02, with the labels that each got.

#25 Misc updates
  .ci-operator.yaml
  .github/ISSUE_TEMPLATE/bug-report.yml
  .snyk
  Makefile
Labels: approved, lgtm

#20 remove pod based webhooks from kueue webhooks
  pkg/configmap/configmap.go
  pkg/configmap/configmap_test.go
  pkg/operator/target_config_reconciler.go
  pkg/webhook/pod_webhook.go
  pkg/webhook/pod_webhook_test.go
Labels: approved, lgtm

#28 fix webhook bug where deployment, pod and statefulset were not dropped
  pkg/operator/target_config_reconciler.go
Labels: approved, lgtm

#29 add Dockerfile for CI
  Dockerfile
  Dockerfile.ci
Labels: approved, lgtm

#27 Add API fields based on feedback from RHOAI
  config/schemapatch/kueue-operator.crd.yaml
  config/schemapatch/operator.openshift.io_kueues.yaml
  deploy/crd/kueue-operator.crd.yaml
  deploy/examples/job.yaml
  manifests/kueue-operator.crd.yaml
  manifests/operator.openshift.io_kueues.yaml
  pkg/apis/kueueoperator/v1alpha1/types.go
  pkg/apis/kueueoperator/v1alpha1/zz_generated.deepcopy.go
  pkg/configmap/configmap.go
  pkg/configmap/configmap_test.go
  pkg/generated/applyconfiguration/kueueoperator/v1alpha1/kueueconfiguration.go
Labels: approved, lgtm

#34 Sync crd to test
  Makefile
  test/e2e/bindata/assets/00_kueue-operator.crd.yaml
Labels: approved, lgtm

#33 remove image from kueue crd
  README.md
  config/schemapatch/kueue-operator.crd.yaml
  config/schemapatch/operator.openshift.io_kueues.yaml
  deploy/crd/kueue-operator.crd.yaml
  deploy/examples/job.yaml
  deploy/examples/rhoai_kueue.yaml
  hack/deploy-ocp.sh
  manifests/kueue-operator.crd.yaml
  manifests/operator.openshift.io_kueues.yaml
  pkg/apis/kueueoperator/v1alpha1/types.go
  pkg/generated/applyconfiguration/kueueoperator/v1alpha1/kueueoperandspec.go
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler.go
  test/e2e/bindata/assets/00_kueue-operator.crd.yaml
  test/e2e/bindata/assets/08_kueue_default.yaml
  test/e2e/e2e_operator_test.go
Labels: approved, lgtm

#36 Installation bugs in readme and bundle generation
  Makefile
  README.md
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
  bundle/manifests/operator.openshift.io_kueues.yaml
  hack/deploy-ocp.sh
  hack/revert-deploy-files.sh
  hack/update-deploy-files.sh
Labels: approved, lgtm, ok-to-test

#35 undeploy.sh : Update operator undeploy steps
  hack/manifests/cert-manager-ocp.yaml
  hack/undeploy-ocp.sh
Labels: approved, lgtm

#37 Refactors of the main reconcile loop
  pkg/operator/target_config_reconciler.go
Labels: approved, lgtm

#31 OCPNODE-2916: add prometheus service monitor
  .gitignore
  bindata/assets/kueue-operator/clusterrolebinding-metrics.yaml
  bindata/assets/kueue-operator/controller-manager-metrics-service.yaml
  bindata/assets/kueue-operator/deployment.yaml
  bindata/assets/kueue-operator/role-prometheus.yaml
  bindata/assets/kueue-operator/rolebinding-prometheus.yaml
  config/schemapatch/kueue-operator.crd.yaml
  config/schemapatch/operator.openshift.io_kueues.yaml
  deploy/crd/kueue-operator.crd.yaml
  go.mod
  manifests/kueue-operator.crd.yaml
  manifests/operator.openshift.io_kueues.yaml
  pkg/apis/kueueoperator/v1alpha1/types.go
  pkg/apis/kueueoperator/v1alpha1/zz_generated.deepcopy.go
  pkg/configmap/configmap.go
  pkg/configmap/configmap_test.go
  pkg/generated/applyconfiguration/kueueoperator/v1alpha1/kueueconfiguration.go
  pkg/operator/target_config_reconciler.go
  test/e2e/bindata/assets/00_kueue-operator.crd.yaml
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/LICENSE
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/resource.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/alertmanager_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/podmonitor_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/probe_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/prometheus_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/prometheusrule_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/servicemonitor_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference
