Repository openshift/kueue-operator, pull requests merged in 2025-07, with the labels that each got.

#420 hack: wait for the packagemanifests to become ready
  hack/deploy-cert-manager.sh
Labels: approved, lgtm

#421 Clean up e2e targets in Makefile
  Makefile
Labels: approved, lgtm

#424 Fix must-gather
  Makefile
Labels: approved, lgtm

#419 switch to use kueue GA repos
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#425 remove coverity task from bundle builds
  .tekton/kueue-bundle-1-0-pull-request.yaml
  .tekton/kueue-bundle-1-0-push.yaml
Labels: approved, lgtm

#430 Clean up e2e targets
  Makefile
Labels: approved, lgtm

#438 Remove colors from e2e output
  Makefile
Labels: approved, lgtm

#445 test: use internal registry image for disconnected clusters
  test/e2e/testutils/builders.go
  test/e2e/testutils/utils.go
Labels: approved, lgtm

#440 OCPNODE-3449: Remove assets generated during the e2e test
  test/e2e/e2e_operator_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/testutils/client.go
  test/e2e/testutils/utils.go
Labels: approved, lgtm, jira/valid-reference

#448 Fix clusterRole clean up
  pkg/operator/target_config_reconciler.go
Labels: approved, lgtm

#449 add mayasa and pannaga as owners to kueue operator repo
  OWNERS
Labels: approved, lgtm

#454 Manually sync operator image in the Bundle
  Makefile
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#460 Remove the deployment of cert-manager from e2e makefile targets
  Makefile
Labels: approved, lgtm

#469 fix auto merge for dockerfiles
  renovate.json
Labels: approved

#468 Add Kueue instance to must-gather
  must-gather/collection-scripts/gather-kueue
Labels: approved, lgtm

#467 OCPNODE-3486: Bump operator version for 1.0.1 release
  Makefile
  README.md
  bundle.Dockerfile
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
  hack/preserve-bundle-labels.sh
Labels: approved, lgtm, jira/valid-reference

#492 copy file filters from release-1.0 on-cel-expression to main pipeline files
  .tekton/kueue-bundle-main-pull-request.yaml
  .tekton/kueue-bundle-main-push.yaml
  .tekton/kueue-must-gather-main-pull-request.yaml
  .tekton/kueue-must-gather-main-push.yaml
  .tekton/kueue-operator-main-pull-request.yaml
  .tekton/kueue-operator-main-push.yaml
Labels: approved, lgtm

#494 use all-pods for oc logs deployment
  hack/wait-for-kueue-leader-election.sh
Labels: approved, lgtm

#497 update bundles to latest builds from main repo
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
Labels: approved, lgtm
