Repository openshift/kueue-operator, pull requests merged in 2025-04, with the labels that each got.

#107 remove assets as this is no longer needed
  assets/kueue/0.10.0/apiservice.yaml
  assets/kueue/0.10.0/clusterrole.yaml
  assets/kueue/0.10.0/clusterrolebinding.yaml
  assets/kueue/0.10.0/kueue.yaml
  assets/kueue/0.10.0/mutatingwebhook.yaml
  assets/kueue/0.10.0/role.yaml
  assets/kueue/0.10.0/rolebinding.yaml
  assets/kueue/0.10.0/service.yaml
  assets/kueue/0.10.0/validatingwebhook.yaml
Labels: approved, lgtm

#108 Preparation for running upstream e2e testsuite
  bindata/assets/kueue-operator/mutatingwebhook.yaml
  bindata/assets/kueue-operator/validatingwebhook.yaml
  hack/sync_manifests.py
  pkg/operator/operatorclient/interfaces.go
  pkg/webhook/pod_webhook.go
  test/e2e/e2e_operator_test.go
Labels: approved, lgtm

#112 Makefile: fetch channel and starting CSV based on OCP version
  Makefile
  hack/deploy-cert-manager.sh
Labels: approved, lgtm

#122 [OCPNODE-3026] bundle-generate: preserve annotations/labels while generating a bundle
  Makefile
  bundle.Dockerfile
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
  bundle/manifests/operator.openshift.io_kueues.yaml
  bundle/metadata/annotations.yaml
  config/schemapatch/kueue-operator.crd.yaml
  deploy/examples/rhoai_kueue.yaml
  hack/preserve-bundle-labels.sh
  hack/revert-deploy-files.sh
Labels: approved, lgtm

#126 add operator image to csv.
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#156 generate required files for basic fbc
  fbc/v4.18/Containerfile.catalog
  fbc/v4.18/catalog-template.yaml
  fbc/v4.18/catalog/catalog.json
Labels: approved, lgtm, ok-to-test

#160 Appstudio kueue fbc 418 plus
  .gitignore
  .tekton/kueue-fbc-418-pull-request.yaml
  .tekton/kueue-fbc-418-push.yaml
  README.md
  fbc/v4.18/Containerfile.catalog
  fbc/v4.18/catalog/kueue-operator/catalog.json
Labels: approved, lgtm, ok-to-test

#164 bindata: sync 0.11.3
  bindata/assets/kueue-operator/clusterrolebinding-metrics-auth.yaml
  bindata/assets/kueue-operator/clusterroles/clusterrole-metrics-auth-role.yaml
  bindata/assets/kueue-operator/clusterroles/clusterrole-topology-editor-role.yaml
  bindata/assets/kueue-operator/clusterroles/clusterrole-topology-viewer-role.yaml
  bindata/assets/kueue-operator/crds/crd-topologies.kueue.x-k8s.io.yaml
  bindata/assets/kueue-operator/role-visibility-server.yaml
Labels: approved, lgtm

#163 add cpmeadors to owners
  OWNERS
Labels: approved, lgtm

#165 use CEL expression to limit fbc konflux jobs to just changes to fbc
  .tekton/kueue-bundle-pull-request.yaml
  .tekton/kueue-fbc-418-pull-request.yaml
  .tekton/kueue-operator-pull-request.yaml
Labels: approved, lgtm, ok-to-test

#168 pkg: disable HierarchialCohorts featuregate
  pkg/configmap/configmap.go
  pkg/configmap/configmap_test.go
Labels: approved, lgtm

#170 use on-cel-expression to filter file changes
  .tekton/kueue-bundle-pull-request.yaml
  .tekton/kueue-fbc-418-pull-request.yaml
  .tekton/kueue-operator-pull-request.yaml
Labels: approved, lgtm, ok-to-test

#173 fix enterprise contracts for kueue operator release 1.0
  .tekton/kueue-bundle-1-0-pull-request.yaml
  .tekton/kueue-bundle-1-0-push.yaml
  .tekton/kueue-operator-1-0-pull-request.yaml
  .tekton/kueue-operator-1-0-push.yaml
Labels: approved

#193 README: Add project status badges
  README.md
Labels: approved, lgtm

#185 remove tekton main from release branches
  .tekton/kueue-bundle-pull-request.yaml
  .tekton/kueue-bundle-push.yaml
  .tekton/kueue-operator-pull-request.yaml
  .tekton/kueue-operator-push.yaml
Labels: approved, lgtm

#204 change image name to the versioned equivalent
  README.md
  fbc/v4.18/catalog-template.yaml
  fbc/v4.18/catalog/kueue-operator/catalog.json
Labels: approved, lgtm

#203 Manually konflux bump release 1.0
  .tekton/kueue-bundle-1-0-pull-request.yaml
  .tekton/kueue-bundle-1-0-push.yaml
  .tekton/kueue-fbc-418-pull-request.yaml
  .tekton/kueue-fbc-418-push.yaml
  .tekton/kueue-operator-1-0-pull-request.yaml
  .tekton/kueue-operator-1-0-push.yaml
Labels: approved, lgtm

#214 Makefile: add e2e targets for prow CI
  Makefile
Labels: approved, lgtm

#222 Update to versioned imageurls
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
Labels: approved, lgtm, ok-to-test

#224 Makefile: fix the commit id for kueue-operator image
  Makefile
Labels: approved, lgtm

#223 Renovate config
  renovate.json
Labels: approved, lgtm

#231 fix renovate configuration issue
  renovate.json
Labels: approved, lgtm

#229 Makefile: refactor e2e Makefile targets
  Makefile
Labels: approved, lgtm

#236 Konflux man update
  .tekton/kueue-bundle-pull-request.yaml
  .tekton/kueue-bundle-push.yaml
  .tekton/kueue-fbc-418-pull-request.yaml
  .tekton/kueue-fbc-418-push.yaml
  .tekton/kueue-operator-pull-request.yaml
  .tekton/kueue-operator-push.yaml
Labels: approved, lgtm

#239 add lgtm and approve to renovate automerge
  renovate.json
Labels: approved, lgtm

#243 use prod repos in CSV
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#242 [release-1.0]: fix make file
  Makefile
Labels: approved, lgtm

#244 [release-1.0] use prod repos in CSV
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#247 add basebranch name as suffix to the renovate PR titles
  renovate.json
Labels: approved, lgtm

#238 OCPNODE-3169: Kueue operand should use readOnlyRootFilesystem
  pkg/configmap/configmap.go
  pkg/configmap/configmap_test.go
  pkg/operator/target_config_reconciler.go
Labels: approved, lgtm, jira/valid-reference

#258 add operator image back to csv
  Makefile
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
  hack/preserve-bundle-labels.sh
Labels: approved, lgtm

#264 use prod operand image
  Makefile
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
  fbc/v4.18/catalog/kueue-operator/catalog.json
  fbc/v4.19/catalog/kueue-operator/catalog.json
  hack/preserve-bundle-labels.sh
Labels: approved, lgtm

#275 Add correct Dockerfile path
  .tekton/kueue-must-gather-pull-request.yaml
  .tekton/kueue-must-gather-push.yaml
Labels: approved, lgtm

#257 Custom must gather image
  Makefile
  must-gather/Dockerfile
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather-kueue
Labels: approved, lgtm
