Repository openshift/kueue-operator, pull requests merged in 2025-09, with the labels that each got.

#594 nudge the CSV for bundles
  .tekton/kueue-operator-main-pull-request.yaml
  .tekton/kueue-operator-main-push.yaml
Labels: approved, lgtm

#600 add nudges for the must-gather and operand push targets
  .tekton/kueue-must-gather-main-push.yaml
  .tekton/kueue-operand-main-push.yaml
Labels: approved, lgtm

#599 use updated sha for clarv scan to fix konflux outage
  .tekton/kueue-bundle-1-0-pull-request.yaml
  .tekton/kueue-bundle-1-0-push.yaml
  .tekton/kueue-bundle-dev-main-pull-request.yaml
  .tekton/kueue-bundle-dev-main-push.yaml
  .tekton/kueue-bundle-main-pull-request.yaml
  .tekton/kueue-bundle-main-push.yaml
  .tekton/kueue-must-gather-1-0-pull-request.yaml
  .tekton/kueue-must-gather-1-0-push.yaml
  .tekton/kueue-must-gather-main-pull-request.yaml
  .tekton/kueue-must-gather-main-push.yaml
  .tekton/kueue-operand-main-pull-request.yaml
  .tekton/kueue-operand-main-push.yaml
  .tekton/kueue-operator-1-0-pull-request.yaml
  .tekton/kueue-operator-1-0-push.yaml
  .tekton/kueue-operator-main-pull-request.yaml
  .tekton/kueue-operator-main-push.yaml
Labels: approved, lgtm

#615 update kueue-0.12 to latest commit
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#593 Local queue default tests
  test/e2e/e2e_local_queue_defaulting_test.go
  test/e2e/e2e_operator_test.go
  test/e2e/testutils/constants.go
  test/e2e/testutils/utils.go
Labels: approved, lgtm

#619 remove unusued make targets
  Makefile
Labels: approved, lgtm

#589 MULTIARCH-5625: Adding support for ppc64le for kueue-operator on release-1.1
  .tekton/kueue-must-gather-1-1-pull-request.yaml
  .tekton/kueue-must-gather-1-1-push.yaml
  .tekton/kueue-operator-1-1-pull-request.yaml
  .tekton/kueue-operator-1-1-push.yaml
Labels: approved, lgtm, jira/valid-reference

#645 fixup readme for submodule
  README.md
Labels: approved, lgtm

#678 add skip-coverity-checks parameter
  .tekton/kueue-bundle-1-1-pull-request.yaml
  .tekton/kueue-bundle-1-1-push.yaml
  .tekton/kueue-must-gather-1-1-pull-request.yaml
  .tekton/kueue-must-gather-1-1-push.yaml
  .tekton/kueue-operator-1-1-pull-request.yaml
  .tekton/kueue-operator-1-1-push.yaml
Labels: approved, lgtm

#676 use related_images.json for the images and bundle
  .tekton/kueue-must-gather-main-push.yaml
  .tekton/kueue-operand-main-push.yaml
  .tekton/kueue-operator-main-push.yaml
  Makefile
  bundle.Dockerfile
  bundle.developer.Dockerfile
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
  deploy/07_deployment.yaml
  deploy/base-csv/kueue-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#689 remove "namespace" from CR example file and rendered CSV
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
  deploy/base-csv/kueue-operator.clusterserviceversion.yaml
  deploy/examples/job.yaml
Labels: approved, lgtm

#707 NO-JIRA: manually update must-gather image on the bundle
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
  related_images.json
Labels: approved, lgtm, jira/valid-reference

#702 OCPKUEUE-280: Enable e2e from submodules
  Makefile
  upstream/kueue/e2e-test-ocp.sh
  upstream/kueue/patch/README.md
  upstream/kueue/patch/e2e.patch
Labels: approved, lgtm, jira/valid-reference

#732 OCPBUGS-62185: add description for kueue cr
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
  deploy/base-csv/kueue-operator.clusterserviceversion.yaml
Labels: approved, jira/severity-low, lgtm, jira/valid-bug, jira/valid-reference

#773 chore(KONFLUX-6210): fix and set name and cpe label for kueue-must-gather-1-0
  must-gather/Dockerfile
Labels: approved, lgtm

#771 chore(KONFLUX-6210): fix and set name and cpe label for kueue-operator-1-0
  Dockerfile
Labels: approved, lgtm

#772 chore(KONFLUX-6210): fix and set name and cpe label for kueue-bundle-1-0
  bundle.Dockerfile
Labels: approved, lgtm
