Repository openshift/kueue-operator, pull requests merged in 2025-03, with the labels that each got.

#55 Drop kueue image and use latest sha.
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
  bundle/manifests/operator.openshift.io_kueues.yaml
Labels: approved

#56 WIP: fixing enterprise contract
  .tekton/kueue-bundle-pull-request.yaml
  .tekton/kueue-bundle-push.yaml
  .tekton/kueue-operator-pull-request.yaml
  .tekton/kueue-operator-push.yaml
  Dockerfile
  bundle.Dockerfile
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
Labels: approved, do-not-merge/work-in-progress

#63 update rpm bundle ref
  .tekton/kueue-bundle-pull-request.yaml
  .tekton/kueue-bundle-push.yaml
  .tekton/kueue-operator-pull-request.yaml
  .tekton/kueue-operator-push.yaml
Labels: approved, ok-to-test

#67 [OCPNODE-2991] pkg/operator: add HA configuration for Kueue deployment
  deploy/07_deployment.yaml
  pkg/configmap/configmap.go
  pkg/configmap/configmap_test.go
  pkg/operator/target_config_reconciler.go
Labels: approved, lgtm

#57 update k8s and kueue in one go
  go.mod
  go.sum
  vendor/k8s.io/code-generator/kube_codegen.sh
  vendor/modules.txt
Labels: approved, lgtm

#71 install via mod flag for ginkgo and controller-gen
  Makefile
Labels: approved, lgtm

#75 bump up memory limits for sast-coverity check
  .tekton/kueue-bundle-pull-request.yaml
  .tekton/kueue-bundle-push.yaml
  .tekton/kueue-operator-pull-request.yaml
  .tekton/kueue-operator-push.yaml
Labels: approved, lgtm

#45 Operator should correctly cleanup operand resources when deleted
  deploy/02_clusterrole.yaml
  deploy/examples/job.yaml
  go.mod
  go.sum
  hack/undeploy-ocp.sh
  pkg/operator/target_config_reconciler.go
  test/e2e/bindata/assets/02_clusterrole.yaml
  test/e2e/e2e_operator_test.go
  vendor/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/errors.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/decode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/encode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/fold.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/fuzz.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/indent.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/scanner.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/stream.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/tables.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/tags.go
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/k8s.io/client-go/metadata/interface.go
  vendor/k8s.io/client-go/metadata/metadata.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/errors.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/restmapper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client_rest_resources.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/codec.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/dryrun.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fieldowner.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fieldvalidation.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/interfaces.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/metadata_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/namespaced_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/object.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/patch.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/typed_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/unstructured_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/watch.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/null.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/warning_handler.go
Labels: approved, lgtm

#77 rebase repo and add docker files
  Dockerfile
  bundle.Dockerfile
Labels: approved, lgtm

#84 Mar 15 konflux patches and drop ecosystem check
  .tekton/kueue-bundle-pull-request.yaml
  .tekton/kueue-bundle-push.yaml
  .tekton/kueue-operator-pull-request.yaml
  .tekton/kueue-operator-push.yaml
Labels: approved, lgtm, ok-to-test

#85 OCPNODE-3007: Do not install alpha crd by default
  pkg/operator/target_config_reconciler.go
  test/e2e/e2e_operator_test.go
Labels: approved, lgtm, jira/valid-reference

#86 add renovate config to hopefully allow for rebasing of PRs
  renovate.json
Labels: approved, lgtm

#102 remove `make images` since we use operator-build
  Makefile
  hack/replace-image.sh
  hack/revert-deploy-files.sh
  hack/update-deploy-files.sh
Labels: approved, lgtm

#103 pkg: add metrics certificates
  pkg/operator/target_config_reconciler.go
Labels: approved, lgtm
