Repository openshift/kueue-operator, pull requests merged in 2025-06, with the labels that each got.

#351 fix typo in HierarchicalCohorts feature gate
  pkg/configmap/configmap.go
  pkg/configmap/configmap_test.go
Labels: approved, lgtm

#354 OCPNODE-3358: add description to RHBok
  bundle.Dockerfile
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
  go.sum
  hack/preserve-bundle-labels.sh
  manifests/operator.openshift.io_kueue.yaml
Labels: approved, lgtm, jira/valid-reference

#357 OCPNODE-3306: Add `ManagedJobsNamespaceSelector` to Kueue configuration
  pkg/configmap/configmap.go
  pkg/configmap/configmap_test.go
  test/e2e/e2e_operator_test.go
Labels: approved, lgtm, jira/valid-reference, ok-to-test

#365 update with latest operator changes
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#372 update bundle to 0.2.0 for tp
  Makefile
  bundle.Dockerfile
  bundle/manifests/kueue-operator.clusterserviceversion.yaml
  hack/preserve-bundle-labels.sh
Labels: approved, lgtm

#396 run must gather even on failure
  Makefile
Labels: approved, lgtm

#347 E2E Testing should use bundle and not make deploy-ocp
  .ci-operator.yaml
  Makefile
  test/e2e/bindata/assets/00_kueue-operator.crd.yaml
  test/e2e/bindata/assets/01_namespace.yaml
  test/e2e/bindata/assets/02_clusterrole.yaml
  test/e2e/bindata/assets/02_role.yaml
  test/e2e/bindata/assets/03_clusterrolebinding.yaml
  test/e2e/bindata/assets/03_rolebinding.yaml
  test/e2e/bindata/assets/04_serviceaccount.yaml
  test/e2e/bindata/assets/05_clusterrole_kueue-batch.yaml
  test/e2e/bindata/assets/06_clusterrole_kueue-admin.yaml
  test/e2e/bindata/assets/07_deployment.yaml
  test/e2e/e2e_operator_test.go
  test/e2e/e2e_suite_test.go
Labels: approved, lgtm

#409 Remove unecessary env vars from e2e tests
  Makefile
  test/e2e/e2e_suite_test.go
Labels: approved, lgtm

#407 test/e2e: address e2e test failure for statefulset
  test/e2e/e2e_operator_test.go
  test/e2e/testutils/builders.go
Labels: approved, lgtm
